spring.application.name=movie-filter-be
spring.profiles.include=supabase, login, api, r2

# Database
spring.jpa.database=postgresql
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.prepare_deferred_statements=false
spring.jpa.generate-ddl=false

spring.jpa.hibernate.ddl-auto=validate