#TMDB
tmdb.api.token=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI2NzQ3OWViMDAxMDY4OGFmOWFkNzJkODEzYWNmMmU1MyIsIm5iZiI6MTc2NTUwNjgwNS45ODgsInN1YiI6IjY5M2I3ZWY1MjFjYmUwNzk0YzBjMTU5NSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.RCXSeV3yChNbN1nFDg-unhON5Ig8-7T9fSYK7SYnulA

#NAVER
naver.client.id=IBJkNeu9urMtpW2oE6vr
naver.client.secret=76fgkR8EKY

#YOUTUBE
youtube.api.key=AIzaSyA2K4FS_5XOMrh6ZbMYT1GfrevMou6V5RY

## sj
# tmdb test api key
tmdb.api.key=fdb28192995b1d3f224fffe05d4da29a
# omdb test api key
omdb.api.key=b71ef913
# ai api key
gemini.api.key=AIzaSyDQyzr4B8j0ckQpsibhk103w2sCDKMkjpU